### ISSUE TITLE
Should the generator really use raw identifiers?

### ISSUE THREAD

**Issue by Lokathor** [maia-s/sdl3-sys-rs#3]
In places where C field names are the same as rust keywords, the generator currently uses a raw identifier so that the exact same name can be used.

However, this means that people *using* the crate need to type `r#` before the field name all the time.

Should we switch to using the type name with an underscore after it, or something else that makes users not need to use the `r#` prefix?

**Comment by revmischa** [comment]
I don't mind the `r#mod` etc at all. RustRover adds it automatically when completing anyway.

**Comment by maia-s** [comment]
rust-analyzer adds it automatically too. E.g. if you have an `SDL_Event` named `event`, type `event.type` and press tab, it's changed to `event.r#type`. You get a popup as you type that show the `type` field is available.

I'm not opposed to changing it to use trailing underscore, but I do like that the raw identifiers use the same name as the original.

**Comment by Lokathor** [comment]
If RA supports it then it's probably fine, since we can generally assume that RA is used by rust programmers.
