### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by revmischa** [maia-s/sdl3-sys-rs#5]
Not sure if I'm doing something wrong but if I try to run an example in sdl3-rs I get:
```
cargo run --example events
...
  = note: Undefined symbols for architecture arm64:
            "_SDL_GetPixelFormatDetails", referenced from:
                _$LT$sdl3..pixels..PixelFormat$u20$as$u20$core..convert..TryFrom$LT$sdl3_sys..generated..pixels..SDL_PixelFormat$GT$$GT$::try_from::h93fac1c73cfca04d in libsdl3-ff9f1e7a60d16101.rlib[111](sdl3-ff9f1e7a60d16101.9r5mrq4xpfh0m2s7rb1yju4av.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

All the symbols seem to be not found. Maybe I'm doing something wrong?

**Comment by maia-s** [comment]
Are you passing any link feature flags to sdl3-sys? By default it'll try to find a dynamic library in the default library search path, but you can change that with features. I added documentation about that to the readme at https://github.com/maia-s/sdl3-sys-rs/tree/main/sdl3-sys#usage recently.

Can you run the `minimal` example in sdl3-sys?

**Comment by maia-s** [comment]
I got your example running here by adding the `build-from-source-static` feature flag to the sdl3-sys dependency. (I'm using that on my macbook because there's no package for sdl3 in brew yet.)

Maybe you'll want to add some feature flags of your own to pass through to sdl3-sys for linking options?

**Comment by revmischa** [comment]
Amazing, thank you! build-from-source worked for me.
Please check if my docs/features are correct: https://github.com/revmischa/sdl3-rs/pull/34
