### ISSUE TITLE
How to use SDL main callbacks?

### ISSUE THREAD

**Issue by revmischa** [maia-s/sdl3-sys-rs#6]
In SDL3 there is an option to use callbacks for your application instead of a main loop because some platforms (iOS/Android/emscripten) call your app back to do things like render a frame: https://wiki.libsdl.org/SDL3/README/main-functions#main-callbacks-in-sdl3

See the snake example: https://github.com/libsdl-org/SDL/blob/main/examples/game/01-snake/snake.c#L294

While the callback function definitions [exist](https://docs.rs/sdl3-sys/0.0.10+SDL-preview-3.1.3/sdl3_sys/main/fn.SDL_AppInit.html) in sdl3-sys, not really sure how we can achieve the same effect as `#define SDL_MAIN_USE_CALLBACKS 1` to tell SDL3 to call back SDL_AppInit/SDL_AppEvent/SDL_AppInit.

**Comment by maia-s** [comment]
I've been working on a proc macro crate for this. If you want to use callbacks in your app, you add the init/event/etc functions and mark them with the appropriate attribute, and the macros do the rest. The intention is for it to allow both the original function signatures and safer ones using e.g. Arc for the app state, so it could be used as-is by the higher level bindings too. I was thinking it's going to be its own crate as it needs some traits for the function signature flexibility

**Comment by revmischa** [comment]
Cool! I was thinking to include a new example that showcases this functionality when it's ready. Wonder if people should be using this setup now for new projects

**Comment by maia-s** [comment]
It could use better docs, but I've published the sdl3-main crate now. I also added the game-01-snake example that uses it
